name: p7_prfix
description: probe
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
dependency_overrides:
  flutter_inappwebview_windows:
    git:
      url: https://github.com/Otzaria/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_windows
flutter:
  uses-material-design: true
