name: p6_terminate
description: probe
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  window_manager: ^0.5.1
flutter:
  uses-material-design: true
